"""Conjecture evaluation loop (Epic Q): the deterministic gate over the sub-agent's judgment.

The judgment is made once, in-session, by a Claude Code sub-agent and committed; this gate
(no model call) checks the artifact is well-formed AND that every evaluated conjecture is
grounded in the real transfer output. Like grounding.verify, the gate is unit-tested to FAIL
on broken input, so it can't rot into a no-op.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
REPO = ROOT.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(REPO / "analogy" / "src"))
sys.path.insert(0, str(REPO / "retrieval" / "src"))
sys.path.insert(0, str(REPO / "grounding" / "src"))

from graphstore.evaluate import VERDICTS, verify

ART = REPO / "graph" / "evaluations" / "conjecture_evaluations.json"


def test_committed_evaluations_pass_the_gate():
    rep = verify(REPO)
    assert rep["passed"]
    assert rep["n_evaluations"] == len(rep["grounded_ok"])    # all grounded in real output
    assert not rep["problems"]


def test_every_projection_is_a_real_transfer_conjecture():
    # the grounding is the point: the gate ties each judgment to a conjecture the pipeline
    # actually generates, so evaluations can't be fabricated independently of the system.
    data = json.loads(ART.read_text())
    for e in data["evaluations"]:
        assert e["projection"] and e["source_base"] and e["source_target"]
        assert e["verdict"] in VERDICTS


def test_verdicts_are_discriminating_not_a_rubber_stamp():
    data = json.loads(ART.read_text())
    verdicts = {e["verdict"] for e in data["evaluations"]}
    # a real judge produced a mix incl. at least one negative call
    assert "implausible" in verdicts and "plausible" in verdicts and len(verdicts) >= 2


def test_headline_conjecture_is_judged_plausible():
    # banach ~~ conformal -> "conformal has a fixed point" recovers conformal self-consistency
    data = json.loads(ART.read_text())
    c1 = next(e for e in data["evaluations"] if e["id"] == "C1")
    assert c1["verdict"] == "plausible"
    assert "BANACH_FIXEDPOINT(cal_test" in c1["projection"]


# --- verify the verifier: the gate must FAIL on tampered artifacts -------------------

def _verify_mutated(mutate):
    data = json.loads(ART.read_text())
    mutate(data)
    # write a throwaway repo view: only the evaluations file is read from disk by verify(),
    # everything else comes from the real corpora, so patch just that file via monkey-load.
    import graphstore.evaluate as ev
    orig = pathlib.Path.read_text

    target = ART

    def fake_read_text(self, *a, **k):
        if self == target:
            return json.dumps(data)
        return orig(self, *a, **k)

    pathlib.Path.read_text = fake_read_text
    try:
        return ev.verify(REPO)
    finally:
        pathlib.Path.read_text = orig


def test_gate_fails_on_invalid_verdict():
    rep = _verify_mutated(lambda d: d["evaluations"][0].__setitem__("verdict", "true"))
    assert not rep["passed"] and rep["problems"]


def test_gate_does_not_rubber_stamp_an_empty_artifact():
    # an artifact with no judged conjectures must NOT pass — a gate with nothing to check is
    # not a green gate (a vacuously-true pass would hide a wiped/empty evaluations file)
    rep = _verify_mutated(lambda d: d.__setitem__("evaluations", []))
    assert not rep["passed"] and rep["n_evaluations"] == 0


def test_gate_fails_on_ungrounded_projection():
    # a projection the transfer pipeline never generates must be rejected
    rep = _verify_mutated(
        lambda d: d["evaluations"][0].__setitem__("projection", "FABRICATED(x, y)"))
    assert not rep["passed"]
    assert any("not generated by transfer" in p for p in rep["problems"])


def test_gate_fails_on_empty_reasoning():
    rep = _verify_mutated(lambda d: d["evaluations"][0].__setitem__("reasoning", "  "))
    assert not rep["passed"]


def test_gate_reports_malformed_artifact_without_crashing():
    import graphstore.evaluate as ev
    orig = pathlib.Path.read_text

    def fake_read_text(self, *a, **k):
        if self == ART:
            return "{ this is not valid json"
        return orig(self, *a, **k)

    pathlib.Path.read_text = fake_read_text
    try:
        rep = ev.verify(REPO)            # must return a report, not raise
    finally:
        pathlib.Path.read_text = orig
    assert not rep["passed"] and rep["problems"]


def test_gate_reports_missing_evaluations_list():
    rep = _verify_mutated(lambda d: d.pop("evaluations"))
    assert not rep["passed"] and any("evaluations" in p for p in rep["problems"])
